## install Xcode
## xcode-select —install
## ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
## save this file
## brew bundle
##
## manual install:
## Google日本語入力: http://www.google.co.jp/ime/
## QuickLock http://www.quicklockapp.com/

update
upgrade

# tap
tap homebrew/binary
tap caskroom/cask
tap caskroom/versions

# cask
install brew-cask

# language
install rbenv
install ruby-build
install go

# scm
install git
install hub
install tig
install mercurial

# shell
install zsh

# editor
install vim
install emacs

# utility
install curl
install autoconf
install automake
install cmake
install tree
install tmux
install nkf
install wget
install readline
install openssl
install jq
install binutils
install coreutils
install lv
install ack
install pass
install s3cmd
install s3fs
install fping
install xz
install ctags
install awscli

# font
install ricty

# cask
cask install iterm2
cask install java7
cask install google-chrome
cask install hipchat
cask install vagrant
cask install alfred
cask install dropbox
cask install virtualbox
cask install firefox
cask install appcleaner
cask install limechat
cask install vlc
cask install skype
cask install xtrafinder
cask install evernote
cask install skitch

# docker
install boot2docker

# middleware
install mysql
install memcached
install redis

# alfred
cask alfred link

# cleanup
cleanup
